--BÀI 1
SELECT MANV,TENNV,
	IIF(PHAI LIKE 'NAM','MR','MRS')AS 'GIỚI TÍNH', 
	NGSINH,YEAR(GETDATE())-YEAR(NGSINH) AS 'TUỔI',
	CASE
		WHEN YEAR(GETDATE())-YEAR(NGSINH) < 18 THEN N'TRẺ EM'
		WHEN YEAR(GETDATE())-YEAR(NGSINH) >=18 AND YEAR(GETDATE())-YEAR(NGSINH) <60 THEN 'LAO ĐỘNG'
		ELSE 'TUỔI GIÀ'
	END AS 'TRẠNG THÁI'
FROM NHANVIEN
--BÀI 2
	BEGIN TRY 
	INSERT INTO THANNHAN VALUES('005','HÙNG','NAM','10-01-1996','TRÙM CUỐI')
	PRINT N'THÊM DỮ LIỆU THÀNH CÔNG'
END TRY
BEGIN CATCH
	
	PRINT N'THÊM DỮ LIỆU THẤT BẠI'
END CATCH
SELECT * FROM THANNHAN
--BÀI 3
	DECLARE @A INT, @N INT, @TONG INT;
	SELECT	@A=1,@N=10,@TONG=0
	WHILE(@A<@N) BEGIN
		IF @A%2 = 0 SET @TONG = @TONG+@A
					SET @A=@A+1
		END
	PRINT(@TONG)
