CREATE DATABASE QLDH
GO
USE QLDH
GO

CREATE TABLE KHACHHANG(
MAKH VARCHAR(10) PRIMARY KEY,
TENKH NVARCHAR(50),
DIACHI NVARCHAR(50),
DIENTHOAI VARCHAR(10),
GIOITINH NVARCHAR(3)

);
CREATE TABLE DONDH(
MADH VARCHAR(10) PRIMARY KEY,
MAKH VARCHAR(10),
NGAYDH DATETIME,
NGAYGH DATETIME
CONSTRAINT FK_DONDH_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

IF OBJECT_ID('SP_KHACHHANG') IS NOT NULL
DROP PROC SP_KHACHHANG
GO
CREATE PROC SP_KHACHHANG 
@MAKH VARCHAR(10),
@TENKH NVARCHAR(50),
@DIACHI NVARCHAR(50),
@DIENTHOAI VARCHAR(10),
@GIOITINH NVARCHAR(3)
AS
IF @MAKH is null or @TENKH is null or @DIACHI is null or @DIENTHOAI is null or @GIOITINH is null
	PRINT 'DỮ LIỆU KHÔNG HỢP LỆ'
ELSE
	INSERT INTO KHACHHANG VALUES (@MAKH,@TENKH,@DIACHI,@DIENTHOAI,@GIOITINH)
	GO
	EXEC SP_KHACHHANG 'KH01',N'HÙNG',N'NAM TỪ LIÊM','0387490099',N'NAM'
	EXEC SP_KHACHHANG 'KH02',N'TOÀN',N'NAM TỪ LIÊM','0949325099',N'NAM'
	SELECT * FROM KHACHHANG

	IF OBJECT_ID('SP_DONDH') IS NOT NULL
DROP PROC SP_DONDH
GO
CREATE PROC SP_DONDH 
@MADH VARCHAR(10),
@MAKH VARCHAR(10),
@NGAYDH DATETIME,
@NGAYGH DATETIME
AS
IF @MADH is null or @MAKH is null or @NGAYDH is null or @NGAYGH is null
	PRINT 'DỮ LIỆU KHÔNG HỢP LỆ'
ELSE
	INSERT INTO KHACHHANG VALUES (@MAKH,@TENKH,@DIACHI,@DIENTHOAI,@GIOITINH)
	GO